name: Build

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: cargo build --verbose
  build-release:
    name: Build Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: cargo build --verbose --release      
