name: Test

on: [push]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: cargo test --verbose
  test-relase:
    name: Tests Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: cargo test --verbose --release